### ISSUE TITLE
Quote in black background

### ISSUE THREAD

**Issue by ofekih** [JessW/QuoteOfTheDay-Cinnamon#5]
This is not really an issue, and it's possible I'm missing something simple, but by default the quote is white text on a black background. In the photo on the website (https://cinnamon-spices.linuxmint.com/desklets/view/16) the text is in a transparent background. Is there any way to remove the black background?

**Comment by JessW** [comment]
Your general desklet settings could be causing the black background.  If you open the Desklets window (e.g. from System Settings), and click the "General Settings" button at the top, does changing "Decoration of desklets" to "No decoration" fix the issue?  If not, send me a screenshot, please!

**Comment by ofekih** [comment]
I am officially incompetent, thanks for the overly kind reply haha!

**Comment by JessW** [comment]
Just glad you're trying out the desklet :)
